# Generated by Django 4.0.4 on 2022-07-09 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=255)),
                ('cor', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('tipo_motor', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Revendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_primary', models.CharField(max_length=20)),
                ('phone_secondary', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bi', models.CharField(max_length=15, unique=True)),
                ('avatar', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Revendedor',
                'verbose_name_plural': 'Revendedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('phone_primary', models.CharField(max_length=20)),
                ('phone_secondary', models.CharField(max_length=20)),
                ('data_visita', models.DateTimeField()),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='api.carro')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User_Revendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.revendedor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doc_Revendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('avatar', models.CharField(max_length=255)),
                ('revendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_revendedores', to='api.revendedor')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Doc_Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('avatar', models.CharField(max_length=255)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_carros', to='api.carro')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Avatar_Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar_carroes', to='api.carro')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Avaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designacao', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avarias', to='api.carro')),
            ],
            options={
                'verbose_name': 'Avaria',
                'verbose_name_plural': 'Avarias',
                'ordering': ['id'],
            },
        ),
    ]
