# Generated by Django 4.0.4 on 2022-07-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc_carro',
            name='avatar',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='doc_revendedor',
            name='avatar',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='revendedor',
            name='avatar',
            field=models.ImageField(upload_to='images'),
        ),
    ]
